%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%           Monte Carlo Estimation Examples            %
%              with MATLAB Implementation              %
%                                                      %
% Author: Ph.D. M.Sc. Eng. Hristo Zhivomirov  02/08/16 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [err, best]=b_est(Seq,k)


%1 dimensional LD sequence generated by LDSNG
x = Seq(1:k);


% % binarynumber 0.10111011010100011
% b = 0.7134246826171875;
% 
% % estimate b as a probability ratio
% % the real value is approx. b/1
% z = find (x<b);
% best = length(z)/length(x);
% 
% err = abs((best - b)/b);

a = 1/3;
% a=0.84270079295*0.5*sqrt(pi);
for i = 1:k
%     xx(i) = exp(-Seq(i)^2);
xx(i) = Seq(i)^2;
end

best = sum(xx)/k;

err = abs((best - a)/a);





end